name = "Intersection"
uuid = "e0dbf9fa-6343-4295-9bff-87e05e90d75c"
authors = ["Adrian Brune <adrian.brune@student-uni.augburg.de>"]
version = "0.0.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
