name = "GeoSpatialRelations"
uuid = "4f4b3779-db02-45a2-a250-b7461b60f8cf"
authors = ["bruneadr "]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1"
LinearAlgebra = "1"
julia = "1.9, 1.10"
